// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -destination=mock_client.go -package=redis -mock_names ClientInterface=MockClient -source=interface.go
//

// Package redis is a generated GoMock package.
package redis

import (
	context "context"
	reflect "reflect"
	time "time"

	redis "github.com/go-redis/redis/v8"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of ClientInterface interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClient)(nil).Close))
}

// Del mocks base method.
func (m *MockClient) Del(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Del", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Del indicates an expected call of Del.
func (mr *MockClientMockRecorder) Del(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockClient)(nil).Del), ctx, key)
}

// DelMany mocks base method.
func (m *MockClient) DelMany(ctx context.Context, keyPattern string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelMany", ctx, keyPattern)
	ret0, _ := ret[0].(error)
	return ret0
}

// DelMany indicates an expected call of DelMany.
func (mr *MockClientMockRecorder) DelMany(ctx, keyPattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelMany", reflect.TypeOf((*MockClient)(nil).DelMany), ctx, keyPattern)
}

// Expire mocks base method.
func (m *MockClient) Expire(ctx context.Context, key string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Expire", ctx, key, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Expire indicates an expected call of Expire.
func (mr *MockClientMockRecorder) Expire(ctx, key, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Expire", reflect.TypeOf((*MockClient)(nil).Expire), ctx, key, ttl)
}

// FlushAll mocks base method.
func (m *MockClient) FlushAll(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FlushAll", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// FlushAll indicates an expected call of FlushAll.
func (mr *MockClientMockRecorder) FlushAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FlushAll", reflect.TypeOf((*MockClient)(nil).FlushAll), ctx)
}

// FlushDB mocks base method.
func (m *MockClient) FlushDB(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FlushDB", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// FlushDB indicates an expected call of FlushDB.
func (mr *MockClientMockRecorder) FlushDB(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FlushDB", reflect.TypeOf((*MockClient)(nil).FlushDB), ctx)
}

// Get mocks base method.
func (m *MockClient) Get(ctx context.Context, key string, obj any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockClientMockRecorder) Get(ctx, key, obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockClient)(nil).Get), ctx, key, obj)
}

// GetKeyValueMap mocks base method.
func (m *MockClient) GetKeyValueMap(ctx context.Context, keyPattern string, data any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeyValueMap", ctx, keyPattern, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetKeyValueMap indicates an expected call of GetKeyValueMap.
func (mr *MockClientMockRecorder) GetKeyValueMap(ctx, keyPattern, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeyValueMap", reflect.TypeOf((*MockClient)(nil).GetKeyValueMap), ctx, keyPattern, data)
}

// GetKeys mocks base method.
func (m *MockClient) GetKeys(ctx context.Context, keyPattern string, obj any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeys", ctx, keyPattern, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetKeys indicates an expected call of GetKeys.
func (mr *MockClientMockRecorder) GetKeys(ctx, keyPattern, obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeys", reflect.TypeOf((*MockClient)(nil).GetKeys), ctx, keyPattern, obj)
}

// GetTTL mocks base method.
func (m *MockClient) GetTTL(ctx context.Context, key string) (time.Duration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTTL", ctx, key)
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTTL indicates an expected call of GetTTL.
func (mr *MockClientMockRecorder) GetTTL(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTTL", reflect.TypeOf((*MockClient)(nil).GetTTL), ctx, key)
}

// HGet mocks base method.
func (m *MockClient) HGet(ctx context.Context, key, field string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HGet", ctx, key, field)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HGet indicates an expected call of HGet.
func (mr *MockClientMockRecorder) HGet(ctx, key, field any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HGet", reflect.TypeOf((*MockClient)(nil).HGet), ctx, key, field)
}

// HGetAll mocks base method.
func (m *MockClient) HGetAll(ctx context.Context, key string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HGetAll", ctx, key)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HGetAll indicates an expected call of HGetAll.
func (mr *MockClientMockRecorder) HGetAll(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HGetAll", reflect.TypeOf((*MockClient)(nil).HGetAll), ctx, key)
}

// HSet mocks base method.
func (m *MockClient) HSet(ctx context.Context, key, field string, value any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HSet", ctx, key, field, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// HSet indicates an expected call of HSet.
func (mr *MockClientMockRecorder) HSet(ctx, key, field, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HSet", reflect.TypeOf((*MockClient)(nil).HSet), ctx, key, field, value)
}

// Inc mocks base method.
func (m *MockClient) Inc(ctx context.Context, key string, num int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inc", ctx, key, num)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Inc indicates an expected call of Inc.
func (mr *MockClientMockRecorder) Inc(ctx, key, num any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inc", reflect.TypeOf((*MockClient)(nil).Inc), ctx, key, num)
}

// Incr mocks base method.
func (m *MockClient) Incr(ctx context.Context, key string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Incr", ctx, key)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Incr indicates an expected call of Incr.
func (mr *MockClientMockRecorder) Incr(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Incr", reflect.TypeOf((*MockClient)(nil).Incr), ctx, key)
}

// IsExist mocks base method.
func (m *MockClient) IsExist(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsExist", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// IsExist indicates an expected call of IsExist.
func (mr *MockClientMockRecorder) IsExist(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsExist", reflect.TypeOf((*MockClient)(nil).IsExist), ctx, key)
}

// IsMemberSet mocks base method.
func (m *MockClient) IsMemberSet(ctx context.Context, key, value string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMemberSet", ctx, key, value)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsMemberSet indicates an expected call of IsMemberSet.
func (mr *MockClientMockRecorder) IsMemberSet(ctx, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMemberSet", reflect.TypeOf((*MockClient)(nil).IsMemberSet), ctx, key, value)
}

// LLen mocks base method.
func (m *MockClient) LLen(ctx context.Context, key string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LLen", ctx, key)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LLen indicates an expected call of LLen.
func (mr *MockClientMockRecorder) LLen(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LLen", reflect.TypeOf((*MockClient)(nil).LLen), ctx, key)
}

// LPop mocks base method.
func (m *MockClient) LPop(ctx context.Context, key string, dest any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LPop", ctx, key, dest)
	ret0, _ := ret[0].(error)
	return ret0
}

// LPop indicates an expected call of LPop.
func (mr *MockClientMockRecorder) LPop(ctx, key, dest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LPop", reflect.TypeOf((*MockClient)(nil).LPop), ctx, key, dest)
}

// LPush mocks base method.
func (m *MockClient) LPush(ctx context.Context, key string, obj any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LPush", ctx, key, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// LPush indicates an expected call of LPush.
func (mr *MockClientMockRecorder) LPush(ctx, key, obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LPush", reflect.TypeOf((*MockClient)(nil).LPush), ctx, key, obj)
}

// LRange mocks base method.
func (m *MockClient) LRange(ctx context.Context, key string, start, stop int64) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LRange", ctx, key, start, stop)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LRange indicates an expected call of LRange.
func (mr *MockClientMockRecorder) LRange(ctx, key, start, stop any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LRange", reflect.TypeOf((*MockClient)(nil).LRange), ctx, key, start, stop)
}

// LRem mocks base method.
func (m *MockClient) LRem(ctx context.Context, key string, count int64, value any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LRem", ctx, key, count, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// LRem indicates an expected call of LRem.
func (mr *MockClientMockRecorder) LRem(ctx, key, count, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LRem", reflect.TypeOf((*MockClient)(nil).LRem), ctx, key, count, value)
}

// LTrim mocks base method.
func (m *MockClient) LTrim(ctx context.Context, key string, start, stop int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LTrim", ctx, key, start, stop)
	ret0, _ := ret[0].(error)
	return ret0
}

// LTrim indicates an expected call of LTrim.
func (mr *MockClientMockRecorder) LTrim(ctx, key, start, stop any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LTrim", reflect.TypeOf((*MockClient)(nil).LTrim), ctx, key, start, stop)
}

// LenList mocks base method.
func (m *MockClient) LenList(ctx context.Context, key string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LenList", ctx, key)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LenList indicates an expected call of LenList.
func (mr *MockClientMockRecorder) LenList(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LenList", reflect.TypeOf((*MockClient)(nil).LenList), ctx, key)
}

// PSubscribe mocks base method.
func (m *MockClient) PSubscribe(ctx context.Context, patterns ...string) *redis.PubSub {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range patterns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PSubscribe", varargs...)
	ret0, _ := ret[0].(*redis.PubSub)
	return ret0
}

// PSubscribe indicates an expected call of PSubscribe.
func (mr *MockClientMockRecorder) PSubscribe(ctx any, patterns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, patterns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PSubscribe", reflect.TypeOf((*MockClient)(nil).PSubscribe), varargs...)
}

// Ping mocks base method.
func (m *MockClient) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockClientMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockClient)(nil).Ping), ctx)
}

// PopList mocks base method.
func (m *MockClient) PopList(ctx context.Context, key string, obj any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PopList", ctx, key, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// PopList indicates an expected call of PopList.
func (mr *MockClientMockRecorder) PopList(ctx, key, obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PopList", reflect.TypeOf((*MockClient)(nil).PopList), ctx, key, obj)
}

// Publish mocks base method.
func (m *MockClient) Publish(ctx context.Context, channel string, message any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, channel, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockClientMockRecorder) Publish(ctx, channel, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockClient)(nil).Publish), ctx, channel, message)
}

// RPop mocks base method.
func (m *MockClient) RPop(ctx context.Context, key string, obj any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RPop", ctx, key, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// RPop indicates an expected call of RPop.
func (mr *MockClientMockRecorder) RPop(ctx, key, obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RPop", reflect.TypeOf((*MockClient)(nil).RPop), ctx, key, obj)
}

// RPush mocks base method.
func (m *MockClient) RPush(ctx context.Context, key string, values ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range values {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RPush", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RPush indicates an expected call of RPush.
func (mr *MockClientMockRecorder) RPush(ctx, key any, values ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, values...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RPush", reflect.TypeOf((*MockClient)(nil).RPush), varargs...)
}

// SAdd mocks base method.
func (m *MockClient) SAdd(ctx context.Context, key string, members ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range members {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SAdd", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SAdd indicates an expected call of SAdd.
func (mr *MockClientMockRecorder) SAdd(ctx, key any, members ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, members...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SAdd", reflect.TypeOf((*MockClient)(nil).SAdd), varargs...)
}

// SCard mocks base method.
func (m *MockClient) SCard(ctx context.Context, key string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SCard", ctx, key)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SCard indicates an expected call of SCard.
func (mr *MockClientMockRecorder) SCard(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SCard", reflect.TypeOf((*MockClient)(nil).SCard), ctx, key)
}

// SIsMember mocks base method.
func (m *MockClient) SIsMember(ctx context.Context, key string, member any) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SIsMember", ctx, key, member)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SIsMember indicates an expected call of SIsMember.
func (mr *MockClientMockRecorder) SIsMember(ctx, key, member any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SIsMember", reflect.TypeOf((*MockClient)(nil).SIsMember), ctx, key, member)
}

// SMembers mocks base method.
func (m *MockClient) SMembers(ctx context.Context, key string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SMembers", ctx, key)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SMembers indicates an expected call of SMembers.
func (mr *MockClientMockRecorder) SMembers(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SMembers", reflect.TypeOf((*MockClient)(nil).SMembers), ctx, key)
}

// SRem mocks base method.
func (m *MockClient) SRem(ctx context.Context, key string, members ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range members {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SRem", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SRem indicates an expected call of SRem.
func (mr *MockClientMockRecorder) SRem(ctx, key any, members ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, members...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SRem", reflect.TypeOf((*MockClient)(nil).SRem), varargs...)
}

// Set mocks base method.
func (m *MockClient) Set(ctx context.Context, key string, ttl time.Duration, obj any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, ttl, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockClientMockRecorder) Set(ctx, key, ttl, obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockClient)(nil).Set), ctx, key, ttl, obj)
}

// SetList mocks base method.
func (m *MockClient) SetList(ctx context.Context, key string, obj any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetList", ctx, key, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetList indicates an expected call of SetList.
func (mr *MockClientMockRecorder) SetList(ctx, key, obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetList", reflect.TypeOf((*MockClient)(nil).SetList), ctx, key, obj)
}

// SetNX mocks base method.
func (m *MockClient) SetNX(ctx context.Context, key string, ttl time.Duration, obj any) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNX", ctx, key, ttl, obj)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetNX indicates an expected call of SetNX.
func (mr *MockClientMockRecorder) SetNX(ctx, key, ttl, obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNX", reflect.TypeOf((*MockClient)(nil).SetNX), ctx, key, ttl, obj)
}

// SetNoExp mocks base method.
func (m *MockClient) SetNoExp(ctx context.Context, key string, obj any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNoExp", ctx, key, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetNoExp indicates an expected call of SetNoExp.
func (mr *MockClientMockRecorder) SetNoExp(ctx, key, obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNoExp", reflect.TypeOf((*MockClient)(nil).SetNoExp), ctx, key, obj)
}

// SetSet mocks base method.
func (m *MockClient) SetSet(ctx context.Context, key string, ttl time.Duration, value any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSet", ctx, key, ttl, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSet indicates an expected call of SetSet.
func (mr *MockClientMockRecorder) SetSet(ctx, key, ttl, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSet", reflect.TypeOf((*MockClient)(nil).SetSet), ctx, key, ttl, value)
}

// SetTTL mocks base method.
func (m *MockClient) SetTTL(ctx context.Context, key string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTTL", ctx, key, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTTL indicates an expected call of SetTTL.
func (mr *MockClientMockRecorder) SetTTL(ctx, key, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTTL", reflect.TypeOf((*MockClient)(nil).SetTTL), ctx, key, ttl)
}

// Subscribe mocks base method.
func (m *MockClient) Subscribe(ctx context.Context, channels ...string) *redis.PubSub {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range channels {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Subscribe", varargs...)
	ret0, _ := ret[0].(*redis.PubSub)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockClientMockRecorder) Subscribe(ctx any, channels ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, channels...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockClient)(nil).Subscribe), varargs...)
}

// TTL mocks base method.
func (m *MockClient) TTL(ctx context.Context, key string) (time.Duration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TTL", ctx, key)
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TTL indicates an expected call of TTL.
func (mr *MockClientMockRecorder) TTL(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TTL", reflect.TypeOf((*MockClient)(nil).TTL), ctx, key)
}

// XAck mocks base method.
func (m *MockClient) XAck(ctx context.Context, stream, group string, ids ...string) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, stream, group}
	for _, a := range ids {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "XAck", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// XAck indicates an expected call of XAck.
func (mr *MockClientMockRecorder) XAck(ctx, stream, group any, ids ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, stream, group}, ids...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "XAck", reflect.TypeOf((*MockClient)(nil).XAck), varargs...)
}

// XAdd mocks base method.
func (m *MockClient) XAdd(ctx context.Context, args *redis.XAddArgs) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "XAdd", ctx, args)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// XAdd indicates an expected call of XAdd.
func (mr *MockClientMockRecorder) XAdd(ctx, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "XAdd", reflect.TypeOf((*MockClient)(nil).XAdd), ctx, args)
}

// XGroupCreate mocks base method.
func (m *MockClient) XGroupCreate(ctx context.Context, stream, group, start string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "XGroupCreate", ctx, stream, group, start)
	ret0, _ := ret[0].(error)
	return ret0
}

// XGroupCreate indicates an expected call of XGroupCreate.
func (mr *MockClientMockRecorder) XGroupCreate(ctx, stream, group, start any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "XGroupCreate", reflect.TypeOf((*MockClient)(nil).XGroupCreate), ctx, stream, group, start)
}

// XGroupCreateMkStream mocks base method.
func (m *MockClient) XGroupCreateMkStream(ctx context.Context, stream, group, start string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "XGroupCreateMkStream", ctx, stream, group, start)
	ret0, _ := ret[0].(error)
	return ret0
}

// XGroupCreateMkStream indicates an expected call of XGroupCreateMkStream.
func (mr *MockClientMockRecorder) XGroupCreateMkStream(ctx, stream, group, start any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "XGroupCreateMkStream", reflect.TypeOf((*MockClient)(nil).XGroupCreateMkStream), ctx, stream, group, start)
}

// XLen mocks base method.
func (m *MockClient) XLen(ctx context.Context, stream string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "XLen", ctx, stream)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// XLen indicates an expected call of XLen.
func (mr *MockClientMockRecorder) XLen(ctx, stream any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "XLen", reflect.TypeOf((*MockClient)(nil).XLen), ctx, stream)
}

// XRange mocks base method.
func (m *MockClient) XRange(ctx context.Context, stream, start, stop string) ([]redis.XMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "XRange", ctx, stream, start, stop)
	ret0, _ := ret[0].([]redis.XMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// XRange indicates an expected call of XRange.
func (mr *MockClientMockRecorder) XRange(ctx, stream, start, stop any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "XRange", reflect.TypeOf((*MockClient)(nil).XRange), ctx, stream, start, stop)
}

// XRangeN mocks base method.
func (m *MockClient) XRangeN(ctx context.Context, stream, start, stop string, count int64) ([]redis.XMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "XRangeN", ctx, stream, start, stop, count)
	ret0, _ := ret[0].([]redis.XMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// XRangeN indicates an expected call of XRangeN.
func (mr *MockClientMockRecorder) XRangeN(ctx, stream, start, stop, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "XRangeN", reflect.TypeOf((*MockClient)(nil).XRangeN), ctx, stream, start, stop, count)
}

// XRead mocks base method.
func (m *MockClient) XRead(ctx context.Context, args *redis.XReadArgs) ([]redis.XStream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "XRead", ctx, args)
	ret0, _ := ret[0].([]redis.XStream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// XRead indicates an expected call of XRead.
func (mr *MockClientMockRecorder) XRead(ctx, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "XRead", reflect.TypeOf((*MockClient)(nil).XRead), ctx, args)
}

// XReadGroup mocks base method.
func (m *MockClient) XReadGroup(ctx context.Context, args *redis.XReadGroupArgs) ([]redis.XStream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "XReadGroup", ctx, args)
	ret0, _ := ret[0].([]redis.XStream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// XReadGroup indicates an expected call of XReadGroup.
func (mr *MockClientMockRecorder) XReadGroup(ctx, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "XReadGroup", reflect.TypeOf((*MockClient)(nil).XReadGroup), ctx, args)
}
